### ISSUE TITLE
CSS hot reloading

### ISSUE THREAD

**Issue by maximhoffman** [kiki-le-singe/react-redux-universal-boilerplate#62]
Hi, big thanks you for your boilerplate. 
Does hot reloading not working right now in your boilerplate? Cuz I tested change body color and it's not reloaded, even after refresh the page. It applied after restart the app. 

UPD. And on class names and Ids doesn't work hash in its names. 
SS: https://cl.ly/0W0X1d1h2P3k

**Comment by kiki-le-singe** [comment]
Hi @maximhoffman thanks for your return.

I just tried and hot reloading doesn't seem to work. But in the `webpack.dev.config` file there is the `reload` option set to true and it works. So you shouldn't have to restart the app. Have you made some changes?

Just for information, soon I'll implement [Dan Abramov](https://github.com/gaearon)'s [react-hot-loader](https://github.com/gaearon/react-hot-loader). It should be better :)

**Comment by kiki-le-singe** [comment]
Hi @maximhoffman
I implemented react-hot-loader and it works. I close this issue.
